In [1]:
import importlib
import cvlac_parser

importlib.reload(cvlac_parser)
from cvlac_parser import *

cargar CvLAC

In [2]:
URL = "https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0001635060"
# URL = 'https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0001584068'
soup = cargar_cvlac(URL)

In [3]:
soup

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
<html>
<head>
<title>CvLAC - RG</title>
<script>
	var texto="";
	var NS4 = (document.layers); // Which browser?
	var IE4 = (document.all);
	var win = window; // window to search.
	var n = 0;

	function resaltar(valor){
	var encontro=0;
	var donde=0;
	//valor=document.getElementById('tt').value;
	reemplazar=RegExp(valor,"i");
	por="<span style=\u0022background-Color:yellow;\u0022>"+valor+"</span>";
	if(texto==""){texto=document.body.innerHTML};
	txt=texto.split(">");
	for (x=0;x<txt.length;x++){
	desde=(txt[x].indexOf("<")!=-1)?txt[x].indexOf("<"):0;
	tempP=txt[x].slice(0,desde);
	tempU=txt[x].slice(desde);
	tempPx=tempP.split(" ");
	for(y=0;y<tempPx.length;y++){
	if(tempPx[y].search(reemplazar)!=-1){
	tempPx[y]=tempPx[y].replace(reemplazar,por);
	encontro+=1;
	}
	}
	txt[x]=tempPx.join(" ")+tempU;
	}
	document.body.innerHTML=txt.join(">");
	//alert((encontro==0)?"No se encontro ''"+valor+"''":"Se encontraron "+encontro+" coincidencias");
	encontro=null;
	donde=null;
	}

	<!-- Original by http://javascript.internet.com More javascripts http://www.hypergurl.com -->

	function findInPage(str) {
	//resaltar(str);
	var txt, i, found; if (str == "") return false; // Find next occurance of the given string on the page, wrap around to the
	// start of the page if necessary.
	if (NS4) { // Look for match starting at the current point. If not found, rewind
	// back to the first match.
	if (!win.find(str)) while(win.find(str, false, true))
	n++; else n++; // If not found in either direction, give message. if (n == 0)
	alert("Not found."); } if (IE4) { txt = win.document.body.createTextRange();
	// Find the nth match from the top of the page.
	for (i = 0; i <= n && (found = txt.findText(str)) != false; i++) { txt.moveStart("character", 1); txt.moveEnd("textedit"); } // If found, mark it and scroll it into view.
	if (found) { txt.moveStart("character", -1); txt.findText(str);
	txt.select(); txt.scrollIntoView(); n++; } // Otherwise, start over at the top of the page and find first match.
	else { if (n > 0) { n = 0; findInPage(str);
	} // Not found anywhere, give message.
	else alert("Not found."); } }
	return false; }
</script>
<meta content="i8iweOHAFYQV0nLnM5KwROxv6enyqJioSpdx0w_uZSI" name="google-site-verification"/>
<meta content="i8iweOHAFYQV0nLnM5KwROxv6enyqJioSpdx0w_uZSI" name="google-site-verification"/>
<link href="/cvlac/css/visualizador.css;jsessionid=2AE1240F0EB15A05957ADC460D0E4BE2" rel="stylesheet" type="text/css"/>
<meta content="no-cache" http-equiv="pragma"/>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
</head>
<body>
<div class="wrapper">
<div class="header">
<div class="menubar">
<ul class="mmenu" style="height:23px;padding:2px;">
<li><a class="menu" href="#" style="width:100px">Datos generales</a>
<ul>
<li><a class="menu" href="#datos_generales">Identificación</a></li>
<li><a class="menu" href="#redes_identificadores">Redes sociales académicas</a></li>
<li><a class="menu" href="#red_identificadores">Identificadores de autor</a></li>
<li><a class="menu" href="#formacion_acad">Formación académica</a></li>
<li><a class="menu" href="#formacion_comp">Formación complementaria</a></li>
<li><a class="menu" href="#estancias_posdoctorales">Estancias posdoctorales</a></li>
<li><a class="menu" href="#experiencia">Experiencia profesional</a></li>
<li><a class="menu" href="#otra_info_personal">Otra información personal</a></li>
</ul>
</li>
<li><a class="menu" href="#" style="width:130px">Actividades formación</a>
<ul>
<li><a class="menu" href="#asesorias">Asesorías</a></li>
<li><a class="menu" href="#curso_corta_du">Cursos de corta duración</a></li>
<li><a class="menu" href="#trabajos_dirigi">Trabajos dirigidos/tutorías</a></li>
</ul>
</li>
<li><a class="menu" href="#" style="width:120px">Actividades evaluador</a>
<ul>
<li><a class="menu" href="#jurado">Jurado comisiones evaluadoras de trabajo de grado</a></li>
<li><a class="menu" href="#par">Par evaluador</a></li>
<li><a class="menu" href="#comite">Participación en comité de evaluación</a></li>
</ul>
</li>
<li><a class="menu" href="#" style="width:130px">Apropiación social</a>
<ul>
<li><a class="menu" href="#edicion">Edición</a></li>
<li><a class="menu" href="#evento">Evento científico</a></li>
<li><a class="menu" href="#re_co">Redes de conocimiento especializado</a></li>
<li><a class="menu" href="#asc_for">Fortalecimiento o solución de asuntos de interés social</a></li>
<li><a class="menu" href="#asc_tra">Trabajo conjunto entre un Centro de Ciencia y un grupo de investigación</a></li>
<li><a class="menu" href="#asc_gen">Generación de insumos de política pública y normatividad</a></li>
<li><a class="menu" href="#asc_cad">Fortalecimiento de cadenas productivas</a></li>
<li><a class="menu" href="#div_ced">Publicaciones editoriales no especializadas</a></li>
<li><a class="menu" href="#div_cda">Producciones de contenido digital Audiovisual</a></li>
<li><a class="menu" href="#div_cds">Producciones de contenido digital Sonoro</a></li>
<li><a class="menu" href="#div_cdr">Producciones de contenido digital Recursos gráficos</a></li>
<li><a class="menu" href="#div_ctr">Producción de estrategias y contenidos transmedia</a></li>
<li><a class="menu" href="#div_des">Desarrollos web</a></li>
</ul>
</li>
<li><a class="menu" href="#" style="width:140px">Producción bibliográfica</a>
<ul>
<li><a class="menu" href="#articulos">Artículos</a></li>
<li><a class="menu" href="#libros">Libros</a></li>
<li><a class="menu" href="#capitulos">Capítulos de libro</a></li>
<li><a class="menu" href="#nota_cientifica">Nota científica</a></li>
<li><a class="menu" href="#textos">Textos en publicaciones no científicas</a></li>
<li><a class="menu" href="#otra_prod_biblio">Otra producción bibliogáfica</a></li>
<li><a class="menu" href="#lib_tra">Traducciones Filológicas y Edición de Fuentes</a></li>
<li><a class="menu" href="#lib_cre">Libro de creación (Piloto)</a></li>
<li><a class="menu" href="#lib_for">Libro de Formación</a></li>
<li><a class="menu" href="#lib_div">Libros de divulgación y/o Compilación de divulgación</a></li>
<li><a class="menu" href="#lib_man">Manuales y Guías Especializadas</a></li>
</ul>
</li>
<li><a class="menu" href="#" style="width:120px">Producción Técnica</a>
<ul>
<li><a class="menu" href="#patentes">Patentes</a></li>
<li><a class="menu" href="#secretos">Secretos empresariales</a></li>
<li><a class="menu" href="#software">Software</a></li>
<li><a class="menu" href="#tecnologicos">Productos tenológicos</a></li>
<li><a class="menu" href="#procesos">Procesos o técnicas</a></li>
<li><a class="menu" href="#trabajos_tec">Trabajos técnicos</a></li>
<li><a class="menu" href="#normas">Normas y Regulaciones</a></li>
<li><a class="menu" href="#otra_prod_tecnica">Otra producción técnica</a></li>
<li><a class="menu" href="#base_tecnologica">Empresas de base tecnologica</a></li>
</ul>
</li>
<li><a class="menu" href="#" style="width:100px">Más información</a>
<ul>
<li><a class="menu" href="#demas_trabajos">Demás Trabajos</a></li>
<li><a class="menu" href="#proyectos">Proyectos</a></li>
</ul>
</li>
<li><a class="menu" href="#" style="width:110px">Producción en arte</a>
<ul>
<li><a class="menu" href="#obras_productos">Obras o productos</a></li>
<li><a class="menu" href="#registros_acuerdo">Registros de acuerdo de licencia</a></li>
<li><a class="menu" href="#crea_cul">Industrias Creativas y culturales</a></li>
<li><a class="menu" href="#even_art">Evento artistico</a></li>
<li><a class="menu" href="#talleres">Talleres creativos</a></li>
</ul>
</li>
<li><a class="menu" href="#" style="width:60px;">Buscar</a><!--[if IE 7]><!--><!--<![endif]-->
<ul>
<li>
<form method="get" name="search" onsubmit="return findInPage(this.string.value);" style="margin:0px;">
<input name="string" onchange="n = 0;" type="text"/><br/>
<input name="search" type="submit" value="Buscar"/>
</form>
</li>
</ul>
</li>
</ul>
</div>
</div>
<div class="sep"> </div>
<div class="container">
<table with="100%">
<tr><td><h3 align="center"><font size="3">Hoja de vida</font></h3></td></tr>
<tr>
<td width="100%"><a name="datos_generales"></a>
<table style="border:#999 1px solid" width="100%">
<tr>
<td class="messageText" colspan="2"><b>Par evaluador reconocido por Minciencias.</b></td>
</tr>
<tr>
<td>Categoría</td>
<td>
                                            Investigador Asociado (I) con vigencia

                                                hasta la publicación de los resultados de la siguiente convocatoria


                                        </td>
</tr>
<tr>
<td>Nombre</td>
<td>
                                        Danny Bercelio González Pinzón
                                    </td>
</tr>
<tr>
<td>Nombre en citaciones</td>
<td>GONZÁLEZ PINZÓN, DANNY BERCELIO</td>
</tr>
<tr>
<td>Nacionalidad</td>
<td>Colombiana</td>
</tr>
<tr>
<td>Sexo</td>
<td>Masculino</td>
</tr>
</table>
</td>
</tr>
<!--INICIO REDES -->
<tr>
<td width="100%"><a name="redes_identificadores"></a>
<table style="border:#999 1px solid" width="100%">
<tr>
<td><h3>Redes sociales académicas</h3></td>
</tr>
<tr>
</tr>
<tr>
<td>
<a href="https://scholar.google.com/citations?user=29zHlFIAAAAJ&amp;hl=es" style="color: #007A81" target="_blank">Google Scholar</a>
</td>
</tr>
<tr>
</tr>
<tr>
<td>
<a href="https://www.linkedin.com/in/berchello/" style="color: #007A81" target="_blank">Linkedln</a>
</td>
</tr>
</table>
</td>
</tr>
<!--                FIN REDES-->
<!--INICIO IDENTIFICADORES -->
<tr>
<td width="100%"><a name="red_identificadores"></a>
<table style="border:#999 1px solid" width="100%">
<tr>
<td><h3>Identificadores de autor</h3></td>
</tr>
<tr>
</tr>
<tr>
<td>
<a href="https://orcid.org/0000-0001-7997-5174" style="color: #007A81" target="_blank">Open Researcher and Contributor ID (ORCID)</a>
</td>
</tr>
<tr>
</tr>
<tr>
<td>
<a href="https://animako.net/berchello/" style="color: #007A81" target="_blank">Otro</a>
</td>
</tr>
</table>
</td>
</tr>
<!--                FIN IDENTIFICADORES-->
<tr>
<td width="100%"><a name="formacion_acad"></a>
<table style="border:#999 1px solid" width="100%">
<tr>
<td colspan="2"><h3>Formación Académica</h3></td>
</tr>
<tr>
<td><li> </li></td>
<td><b>Maestría/Magister</b>
                            FUNDACIÓN UNIVERSITARIA LOS LIBERTADORES<br/>
                            MAESTRÍA EN COMUNICACIÓN CREATIVA<br/>
                            Agostode2020 - Noviembrede 2022<br/>
                            Un Viaje Ligero: Proceso de creación narrativa para promover prácticas ambientales responsables, desde la literatura ecológica en niños y niñas de preescolar.</td>
</tr>
<tr>
<td><li> </li></td>
<td><b>Especialización</b>
                            UNIVERSIDAD NACIONAL DE COLOMBIA SEDE BOGOTA<br/>
                            ESPECIALIZACION EN ANIMACION<br/>
                            Juliode2013 - Septiembrede 2014<br/>
                            Un Viaje Ligero</td>
</tr>
<tr>
<td><li> </li></td>
<td><b>Pregrado/Universitario</b>
                            UNIVERSIDAD MILITAR NUEVA GRANADA<br/>
                            INGENIERIA EN MULTIMEDIA<br/>
                            Enerode2002 - Juliode 2007<br/>
                            Diseño y Creación del Paquete de Identidad Televisiva del Programa Institucional "A Mover el Camello" de la Universidad Militar Nueva Granada.</td>
</tr>
</table>
</td>
</tr>
<tr>
<td width="100%"><a name="formacion_comp"></a>
</td>
</tr>
<tr>
<td width="100%"><a name="estancias_posdoctorales"></a>
</td>
</tr>
<tr>
<td width="100%"><a name="experiencia"></a>
<table style="border:#999 1px solid" width="100%">
<tr>
<td colspan="2"><h3>Experiencia profesional</h3></td>
</tr>
<tr>
<td><li> </li></td>
<td>
<b>UNIVERSIDAD MILITAR NUEVA GRANADA</b><br/>
<i>Dedicación: </i>40 horas Semanales
                        Septiembre de 2023
                         de Actual<br/><br/>
</td>
</tr>
<tr>
<td><li> </li></td>
<td>
<b>Universidad Nacional Abierta y a Distancia - UNAD</b><br/>
<i>Dedicación: </i>20 horas Semanales
                        Septiembre de 2023
                        Diciembre de 2024<br/><br/>
</td>
</tr>
<tr>
<td><li> </li></td>
<td>
<b>UNIVERSIDAD MILITAR NUEVA GRANADA</b><br/>
<i>Dedicación: </i>9 horas Semanales
                        Julio de 2007
                        Agosto de 2023<br/><br/>
</td>
</tr>
<tr>
<td><li> </li></td>
<td>
<b>UNIVERSIDAD DE SAN BUENAVENTURA - SEDE BOGOTA</b><br/>
<i>Dedicación: </i>40 horas Semanales
                        Julio de 2015
                        Diciembre de 2022<br/><br/>
<span class="blueTitle">Actividades de investigación</span><br/>

                        -
                        Investigación y Desarrollo
                        <i> - Titulo:</i>  Docente Investigador vinculado al grupo de investigación SOLSYTEC, Tutor en los semilleros GAMDEV# y ANIMOV, adscritos al programa de Ingeniería Multimedia de la Facultad de Ingeniería.

Dedicación: 10 horas Semanales.
                        Julio 2016
                        Diciembre 2022<br/>
</td>
</tr>
<tr>
<td><li> </li></td>
<td>
<b>SERVICIO NACIONAL DE APRENDIZAJE SENA</b><br/>
<i>Dedicación: </i>40 horas Semanales
                        Julio de 2010
                        Diciembre de 2015<br/><br/>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td width="100%"><a name="otra_info_personal"></a>
<table style="border:#999 1px solid" width="100%">
<tr>
<td><h3>Áreas de actuación</h3></td>
</tr>
<tr>
<td><li> Ingeniería y Tecnología -- Otras Ingenierías y Tecnologías -- Otras Ingenierías y Tecnologías</li></td>
</tr>
<tr>
<td><li> Ingeniería y Tecnología -- Ingenierías Eléctrica, Electrónica e Informática -- Ingeniería de Sistemas y Comunicaciones</li></td>
</tr>
<tr>
<td><li> Ciencias Sociales -- Periodismo y Comunicaciones -- Medios y Comunicación Social</li></td>
</tr>
<tr>
<td><li> Humanidades -- Arte -- Artes audiovisuales</li></td>
</tr>
<tr>
<td><li> Humanidades -- Arte -- Diseño</li></td>
</tr>
<tr>
<td><li> Humanidades -- Arte -- Otras artes</li></td>
</tr>
</table>
</td>
</tr>
<tr>
<td width="100%"></td>
</tr>
<tr>
<td width="100%">
<table style="border:#999 1px solid" width="100%">
<tr>
<td><h3>Líneas de investigación</h3></td>
</tr>
<tr>
<td><li> Contenidos Digitales y Diseño de Experiencias Inmersivas., <i>Activa:</i>Si</li></td>
</tr>
</table>
</td>
</tr>
<tr>
<td width="100%">
<table style="border:#999 1px solid" width="100%">
<tr>
<td><h3>Reconocimientos</h3></td>
</tr>
<tr>
<td><li>2do Festival de Cortometrajes de Chia 2018 - 2do Lugar.,Alcaldía Chia - Octubrede 2018</li></td>
</tr>
<tr>
<td><li>Festival Equinoxio 17 - Selección Oficial
septiembre de 2014
Mejor Cortometraje de Animación
"Un Viaje Ligero"
Dir. Danny Gonzalez,UNIVERSIDAD NACIONAL DE COLOMBIA SEDE BOGOTA - Septiembrede 2014</li></td>
</tr>
<tr>
<td><li>Festival CineGlobe 2015 - Selección Oficial
CineGlobe - Festival International de Films au CERN - INSPIRÉ PAR LA SCIENCE
Special Kids and Family Session
"Un Viaje Ligero"
Dir. Danny González, - Marzode 2015</li></td>
</tr>
<tr>
<td><li>Mentor - Google Startup Weekend - Chía Sabana Centro.,Alcaldía Chia - Septiembrede 2015</li></td>
</tr>
<tr>
<td><li>Distinción Meritoria Proyecto de Grado - Maestría en Comunicación Creativa,FUNDACIÓN UNIVERSITARIA LOS LIBERTADORES - Noviembrede 2022</li></td>
</tr>
<tr>
<td><li>Campus Party Colombia 2019 - Campus Party University - Workshop - Programación para Animadores en Autodesk Maya.,FONTIC (MINTIC) - Juniode 2019</li></td>
</tr>
</table>
</td>
</tr>
<tr>
<td align="right" width="100%"> </td>
</tr>
<tr>
<td><blockquote class="fillText">Los ítems de producción con la marca  <img height="15px" src="/cvlac/images/chulo.jpg" width="15px"/> corresponden a productos avalados y validados para la última <i>Convocatoria Nacional para el Reconocimiento y Medición de Grupos de Investigación, Desarrollo Tecnológico o de Innovación y para el Reconocimiento de Investigadores del SNCTeI</i></blockquote></td>
</tr>
<!--Inicio asesorias-->
<tr>
<td width="100%"><a name="asesorias"></a></td>
</tr>
<!--Fin asesorias-->
<!--Inicio curso corta -->
<tr>
<td width="100%"><a name="curso_corta_du"></a></td>
</tr>
<!--Fin curso corta-->
<!--Inicio trabajos dirigidos-->
<tr>
<td width="100%"><a name="trabajos_dirigi"></a> <table style="border:#999 1px solid" width="100%">
<tr>
<td><h3>Trabajos dirigidos/tutorías</h3></td>
</tr>
<tr>
<td><li>
<b>Trabajos dirigidos/Tutorías - Trabajos de grado de pregrado</b></li>
</td>
</tr>
<tr>
<td>
<blockquote>

                            DANNY BERCELIO GONZALEZ PINZON,

                            Desarrollo de la aplicación interactiva con el libro ¿Mandrágora¿, enriquecido con contenidos en realidad aumentada, para reforzar el proceso de lectura en niños de primera infancia.
                            UNIVERSIDAD DE SAN BUENAVENTURA - SEDE BOGOTA
                            Estado: Tesis concluida
                            Ingeniería Multimedia,
                             2021.
                            <i>Dirigió como: </i>Tutor principal,
                             <i>Persona(s) orientada(s): </i>




                            Tutor(es)/Cotutor(es): DANNY BERCELIO GONZALEZ PINZON , JOHANA CAROLINA MARTINEZ BALLESTEROS,

                            <br/><b>Areas: </b><br/>

                            Ingeniería y Tecnología -- Otras Ingenierías y Tecnologías -- Otras Ingenierías y Tecnologías,


                        </blockquote>
</td>
</tr>
<tr>
<td><li>
<img height="15px" src="/cvlac/images/chulo.jpg" width="15px"/>
<b>Trabajos dirigidos/Tutorías - Trabajos de grado de pregrado</b></li>
</td>
</tr>
<tr>
<td>
<blockquote>

                            DANNY BERCELIO GONZALEZ PINZON,

                            Desarrollo Web de Sala de Conferencias con acceso a Streaming de Video y Herramientas de apoyo.
                            UNIVERSIDAD DE SAN BUENAVENTURA - SEDE BOGOTA
                            Estado: Tesis concluida
                            Ingeniería Multimedia,
                             2021.
                            <i>Dirigió como: </i>Tutor principal,
                             <i>Persona(s) orientada(s): </i>

                            Karen Vanessa Ariza Hernandez
                            Juan Sebastian Madrid Palendia



                            Tutor(es)/Cotutor(es): DANNY BERCELIO GONZALEZ PINZON , JOHANA CAROLINA MARTINEZ BALLESTEROS,

                            <br/><b>Areas: </b><br/>

                            Ingeniería y Tecnología -- Otras Ingenierías y Tecnologías -- Otras Ingenierías y Tecnologías,


                        </blockquote>
</td>
</tr>
<tr>
<td><li>
<img height="15px" src="/cvlac/images/chulo.jpg" width="15px"/>
<b>Trabajos dirigidos/Tutorías - Trabajo de grado de maestría o especialidad clínica</b></li>
</td>
</tr>
<tr>
<td>
<blockquote>

                            DANNY BERCELIO GONZALEZ PINZON,

                            Un viaje ligero: Proceso de creación narrativa para promover prácticas ambientales responsables, desde la literatura ecológica en niños y niñas de preescolar
                            FUNDACIÓN UNIVERSITARIA LOS LIBERTADORES
                            Estado: Tesis concluida
                            MAESTRÍA EN COMUNICACIÓN CREATIVA,
                             2021.
                            <i>Dirigió como: </i>Tutor principal,
                             <i>Persona(s) orientada(s): </i>

                            Danny Bercelio González Pinzón



                            Tutor(es)/Cotutor(es): INGRID ZACIPA INFANTE,

                            <br/><b>Areas: </b><br/>

                            Ciencias Sociales -- Periodismo y Comunicaciones -- Medios y Comunicación Social,

## Artículos

In [4]:
df_articulos = articulos_a_dataframe(soup)
df_articulos.sort_values(by='anio').reset_index().drop(columns='index')

,autores,titulo,revista,issn,editorial,volumen,fasciculo,paginas,anio,doi,autores_texto,n_autores,primer_autor,ultimo_autor
0,"[DANNY BERCELIO GONZALEZ PINZON, BELMAN JAHIR ...",Psychophysiological Analysis of Sound Stimuli,Colombia Visión Electrónica: Algo Más Que Un E...,1909-9746,Fondo De Publicaciones De La Universidad Distr...,17,N/A,263-284,2023,10.14483/issn.2248-4728,DANNY BERCELIO GONZALEZ PINZON; BELMAN JAHIR R...,3,DANNY BERCELIO GONZALEZ PINZON,MARCELO HERRERA MARTINEZ

## Eventos

In [5]:
df_eventos = extraer_eventos_cientificos(soup)
df_eventos.sort_values(by='fecha').reset_index().drop(columns='index')

,nombre_evento,tipo_evento,ambito,fecha,lugar,institucion,tipo_vinculacion,producto,tipo_producto,participante,rol
0,Congreso Internacional de Innovación y Tendenc...,Congreso,Internacional,,,,,,,,
1,Congreso Internacional de Innovación y Tendenc...,Congreso,Internacional,,,UNIVERSIDAD DE SAN BUENAVENTURA - SEDE BOGOTA,Patrocinadora,Organizational Model Proposal for the Creation...,Producción bibliográfica - Trabajos en eventos...,DANNY BERCELIO GONZALEZ PINZON,Ponente
2,Congreso Internacional de Innovación y Tendenc...,Congreso,Internacional,,,UNIVERSIDAD DE SAN BUENAVENTURA - SEDE BOGOTA,Patrocinadora,Organizational Model Proposal for the Creation...,Producción técnica - Presentación de trabajo -...,DANNY BERCELIO GONZALEZ PINZON,Ponente
3,II Congreso Internacional de Ciencias Básicas ...,Congreso,Internacional,,,UNIVERSIDAD DE SAN BUENAVENTURA - SEDE BOGOTA,Gestionadora,Mobile Interactive Application for Neuropsycho...,Producción bibliográfica - Trabajos en eventos...,DANNY BERCELIO GONZALEZ PINZON,Ponente
4,II Congreso Internacional de Ciencias Básicas ...,Congreso,Internacional,,,UNIVERSIDAD DE SAN BUENAVENTURA - SEDE BOGOTA,Gestionadora,Mobile Interactive Application for Neuropsycho...,Producción técnica - Presentación de trabajo -...,DANNY BERCELIO GONZALEZ PINZON,Ponente

## Trabajos dirigidos

In [6]:
df_trabajosdirigidos = extraer_trabajos_dirigidos(soup)
df_trabajosdirigidos.head(3)

,tipo_trabajo,titulo,institucion,estado,programa,anio,tipo_orientacion,persona_orientada,tutores_cotutores,areas
0,Trabajos de grado de pregrado,Desarrollo de la aplicación interactiva con el...,UNIVERSIDAD DE SAN BUENAVENTURA - SEDE BOGOTA,Tesis concluida,Ingeniería Multimedia,2021,Tutor principal,,"DANNY BERCELIO GONZALEZ PINZON , JOHANA CAROLI...",Ingeniería y Tecnología -- Otras Ingenierías y...
1,Trabajos de grado de pregrado,Desarrollo Web de Sala de Conferencias con acc...,UNIVERSIDAD DE SAN BUENAVENTURA - SEDE BOGOTA,Tesis concluida,Ingeniería Multimedia,2021,Tutor principal,Karen Vanessa Ariza Hernandez,"DANNY BERCELIO GONZALEZ PINZON , JOHANA CAROLI...",Ingeniería y Tecnología -- Otras Ingenierías y...
2,Trabajos de grado de pregrado,Desarrollo Web de Sala de Conferencias con acc...,UNIVERSIDAD DE SAN BUENAVENTURA - SEDE BOGOTA,Tesis concluida,Ingeniería Multimedia,2021,Tutor principal,Juan Sebastian Madrid Palendia,"DANNY BERCELIO GONZALEZ PINZON , JOHANA CAROLI...",Ingeniería y Tecnología -- Otras Ingenierías y...

## Obras o productos

In [7]:
df_obras = extraer_obras_productos(soup)

df_obras

,nombre_producto,disciplina,fecha_creacion,espacio_evento,fecha_presentacion,entidad_convocante
0,"El Regalo que Germina, Parte 4",Humanidades -- Arte -- Artes audiovisuales,Noviembre de 2022,USBMEDIASHOW 2022-2,2022-11-11,UNIVERSIDAD DE SAN BUENAVENTURA - SEDE BOGOTA
1,"El Regalo que Germina, Parte 3",Humanidades -- Arte -- Artes audiovisuales,Noviembre de 2022,USBMEDIASHOW 2022-2,2022-11-11,UNIVERSIDAD DE SAN BUENAVENTURA - SEDE BOGOTA
2,"El viaje de Balam, Parte 1",Humanidades -- Arte -- Artes audiovisuales,Noviembre de 2022,USBMEDIASHOW 2022-2,2022-11-11,UNIVERSIDAD DE SAN BUENAVENTURA - SEDE BOGOTA
3,"El viaje de Balam, Parte 2",Humanidades -- Arte -- Artes audiovisuales,Noviembre de 2022,USBMEDIASHOW 2022-2,2022-11-11,UNIVERSIDAD DE SAN BUENAVENTURA - SEDE BOGOTA
4,"El viaje de Balam, Parte 3",Humanidades -- Arte -- Artes audiovisuales,Noviembre de 2022,USBMEDIASHOW 2022-2,2022-11-11,UNIVERSIDAD DE SAN BUENAVENTURA - SEDE BOGOTA
...,...,...,...,...,...,...
94,Shortfilm - Un Viaje Ligero,Humanidades -- Arte -- Artes audiovisuales,Junio de 2014,Festival CineGlobe 2015 - Festival Internation...,2015-03-29,UNIVERSIDAD NACIONAL DE COLOMBIA SEDE BOGOTA
95,Shortfilm - Vuela (Jhon Jairo Villalba),Humanidades -- Arte -- Artes audiovisuales,Junio de 2014,Premios Anita,2014-11-28,Universidad Jorge Tadeo Lozano
96,Shortfilm - Luna (Gabriel Zarate),Humanidades -- Arte -- Artes audiovisuales,Junio de 2014,Premios Anita,2014-11-28,Universidad Jorge Tadeo Lozano
97,Shortfilm - Cielo Nublado (Lorena Martinez),Humanidades -- Arte -- Artes audiovisuales,Junio de 2014,Premios Anita,2014-11-28,Universidad Jorge Tadeo Lozano
98,Guion - Un Viaje Ligero,Humanidades -- Arte -- Artes audiovisuales,Mayo de 2014,,,

In [8]:
inspeccionar_seccion(
    soup,
    "Proyectos",
    limite=5
)

======================================================================
SECCIÓN: Proyectos
======================================================================

--- FILA 0 ---
Proyectos

HTML:
<tr>
 <td id="proyectos">
  <h3>
   Proyectos
  </h3>
 </td>
</tr>


--- FILA 1 ---
Tipo de proyecto: | Investigación-Creación | Diseño de un laboratorio virtual para el entrenamiento en habilidades y competencias en regulación emocional (FASE I). | Inicio: | Febrero
                        2022 | Fin: | Noviembre
                        2022 | Duración | Resumen | Las señales de electroencefalografía (EEG) han captado el interés de la comunidad científica; actualmente, la mayoría de las investigaciones están enfocadas a cómo estas señales reflejan la respuesta psicofisiológica de las personas, en términos emocionales, respecto a diferentes estímulos; por esta razón, en este documento se presenta el análisis de señales de EEG captadas por el headset de NeuroSky ante estímulos sonoros con contenido emocional provenientes de la IADS (International Affective Digital Sounds); además, se analizaron algunas señales del dataset de EEG ¿DREAMER¿. De este desarrollo se llegó a que hay una correspondencia entre los valores de Valencia y Arousal con las bandas de frecuencia de EEG, observando además que, para el caso del DREAMER, los electrodos correspondientes al hemisferio derecho presentaban la mayoría de la energía en el cerebro.

HTML:
<tr>
 <td>
  <blockquote>
   <i>
    Tipo de proyecto:
   </i>
   Investigación-Creación
   <br/>
   Diseño de un laboratorio virtual para el entrenamiento en habilidades y competencias en regulación emocional (FASE I).
   <br/>
   <i>
    Inicio:
   </i>
   Febrero
                        2022
   <i>
    Fin:
   </i>
   Noviembre
                        2022
   <i>
    Duración
   </i>
   <br/>
   <b>
    Resumen
   </b>
   <p class="test1">
    Las señales de electroencefalografía (EEG) han captado el interés de la comunidad científica; actualmente, la mayoría de las investigaciones están enfocadas a cómo estas señales reflejan la respuesta psicofisiológica de las personas, en términos emocionales, respecto a diferentes estímulos; por esta razón, en este documento se presenta el análisis de señales de EEG captadas por el headset de NeuroSky ante estímulos sonoros con contenido emocional provenientes de la IADS (International Affective Digital Sounds); además, se analizaron algunas señales del dataset de EEG ¿DREAMER¿. De este desarrollo se llegó a que hay una correspondencia entre los valores de Valencia y Arousal con las bandas de frecuencia de EEG, observando además que, para el caso del DREAMER, los electrodos correspondientes al hemisferio derecho presentaban la mayoría de la energía en el cerebro.
    <br/>
   </p>
  </blockquote>
 </td>
</tr>


--- FILA 2 ---
Tipo de proyecto: | Investigación y desarrollo | Narrativas transmedia para la memoria histórica y la construcción de paz. Capitulo II. SURA | Inicio: | Junio
                        2022 | Fin: | Noviembre
                        2022 | Duración | Resumen | La plataforma ¿Desarmando Cuentos: Narrativas digitales infantiles para la construcción de paz¿ busca desarrollar y producir contenidos digitales orientados hacia las dinámicas presentes en los procesos de memoria histórica y la construcción de paz.

Este proyecto se construye a partir de un ejercicio multidisciplinar a partir de las áreas sociales, jurídicas, artísticas y de ingeniería con el propósito de transmitir a las nuevas generaciones los relatos de resiliencia en el marco del conflicto.

HTML:
<tr>
 <td>
  <blockquote>
   <i>
    Tipo de proyecto:
   </i>
   Investigación y desarrollo
   <br/>
   Narrativas transmedia para la memoria histórica y la construcción de paz. Capitulo II. SURA
   <br/>
   <i>
    Inicio:
   </i>
   Junio
                        2022
   <i>
    Fin:
   </i>
   Noviembre
                        2022
   <i>
    Duración
   </i>
   <br/>
   <b>
    Resumen
   </b>
   <p class="test1">
    La plataforma ¿Desarmando Cuentos: Narrativas digitales infantiles para la construcción de paz¿ busca desarrollar y producir contenidos digitales orientados hacia las dinámicas presentes en los procesos de memoria histórica y la construcción de paz.

Este proyecto se construye a partir de un ejercicio multidisciplinar a partir de las áreas sociales, jurídicas, artísticas y de ingeniería con el propósito de transmitir a las nuevas generaciones los relatos de resiliencia en el marco del conflicto.
    <br/>
   </p>
  </blockquote>
 </td>
</tr>


--- FILA 3 ---
Tipo de proyecto: | Investigación-Creación | Mindfulness en realidad virtual para apoyar los procesos de relajación | Inicio: | Agosto
                        2021 | Fin: | Noviembre
                        2021 | Duración | Resumen | El Proyecto busca a traves de un sistema de Realidad Virtual innovar en técnicas de Mindfulness para apoyar procesos de relajación.

HTML:
<tr>
 <td>
  <blockquote>
   <i>
    Tipo de proyecto:
   </i>
   Investigación-Creación
   <br/>
   Mindfulness en realidad virtual para apoyar los procesos de relajación
   <br/>
   <i>
    Inicio:
   </i>
   Agosto
                        2021
   <i>
    Fin:
   </i>
   Noviembre
                        2021
   <i>
    Duración
   </i>
   <br/>
   <b>
    Resumen
   </b>
   <p class="test1">
    El Proyecto busca a traves de un sistema de Realidad Virtual innovar en técnicas de Mindfulness para apoyar procesos de relajación.
    <br/>
   </p>
  </blockquote>
 </td>
</tr>


--- FILA 4 ---
Tipo de proyecto: | Investigación-Creación | Contarte: Narrativas transmedia para la memoria histórica y la construcción de paz. | Inicio: | Septiembre
                        2020 | Fin: | Agosto
                        2021 | Duración | Resumen | El objetivo es fortalecer procesos locales y regionales de organizaciones de la sociedad civil que practiquen la construcción de paz y la memoria histórica a través de la producción, difusión e intercambio de conocimientos endógenos, académicos y artísticos por medio de narrativas transmedia.

HTML:
<tr>
 <td>
  <blockquote>
   <img height="15px" src="/cvlac/images/chulo.jpg" width="15px"/>
   <i>
    Tipo de proyecto:
   </i>
   Investigación-Creación
   <br/>
   Contarte: Narrativas transmedia para la memoria histórica y la construcción de paz.
   <br/>
   <i>
    Inicio:
   </i>
   Septiembre
                        2020
   <i>
    Fin:
   </i>
   Agosto
                        2021
   <i>
    Duración
   </i>
   <br/>
   <b>
    Resumen
   </b>
   <p class="test1">
    El objetivo es fortalecer procesos locales y regionales de organizaciones de la sociedad civil que practiquen la construcción de paz y la memoria histórica a través de la producción, difusión e intercambio de conocimientos endógenos, académicos y artísticos por medio de narrativas transmedia.
    <br/>
   </p>
  </blockquote>
 </td>
</tr>